herename: Ahmed Hamam Daily Bot
on:
  schedule:
    - cron: '0 7 * * *'  # 9 ุตุจุงุญุงู ุจุชูููุช ูุตุฑ
    - cron: '0 14 * * *' # 4 ุนุตุฑุงู ุจุชูููุช ูุตุฑ
    - cron: '0 22 * * *' # 12 ูุณุงุกู ุจุชูููุช ูุตุฑ
  workflow_dispatch:     # ูุฐุง ุงูุณุทุฑ ููุธูุฑ ูู ุฒุฑ ุงูุชุดุบูู ุงููุฏูู

jobs:
  broadcast:
    runs-on: ubuntu-latest
    steps:
      - name: Send Daily Messages
        shell: bash
        run: |
          TOKEN="8547376425:AAGHy5gDX7gaNI9c9r2L4mdvvu7YxIObyEk"
          CHANNEL="@AhmedMods2"
          HEADER="๐คฒ <b>ุงุฏุนูุง ูุฃุญูุฏ ููุงู</b>"
          
          # ุชุญุฏูุฏ ุงูุณุงุนุฉ ุงูุญุงููุฉ
          HOUR=$(date +%H)
          
          if [ "$HOUR" == "07" ]; then
            # ูุฑุฏ ุงูุตุจุงุญ (20 ุฑุณุงูุฉ)
            for i in {1..20}; do
              RES=$(curl -s "https://api.aladhan.com/v1/ayah/random/ar.alafasy")
              TXT=$(echo $RES | jq -r '.data.text')
              SUR=$(echo $RES | jq -r '.data.surah.name')
              if [ "$TXT" != "null" ]; then
                curl -s -X POST "https://api.telegram.org/bot$TOKEN/sendMessage" \
                -d "chat_id=$CHANNEL" -d "parse_mode=HTML" \
                -d "text=$HEADER%0A%0Aโ๏ธ <b>ูุฑุฏ ุงูุตุจุงุญ ($i/20)</b>%0A%0A$TXT%0A%0A๐ ุณูุฑุฉ: $SUR"
                sleep 2
              fi
            done

          elif [ "$HOUR" == "14" ]; then
            # ูุฑุฏ ุงูุนุตุฑ (10 ุฑุณุงุฆู)
            for i in {1..10}; do
              RES=$(curl -s "https://api.aladhan.com/v1/ayah/random/ar.alafasy")
              TXT=$(echo $RES | jq -r '.data.text')
              if [ "$TXT" != "null" ]; then
                curl -s -X POST "https://api.telegram.org/bot$TOKEN/sendMessage" \
                -d "chat_id=$CHANNEL" -d "parse_mode=HTML" \
                -d "text=$HEADER%0A%0A๐ค๏ธ <b>ูุฑุฏ ุงูุนุตุฑ ($i/10)</b>%0A%0A$TXT"
                sleep 2
              fi
            done

          else
            # ูุฑุฏ ุงููุณุงุก (ุฃุฐูุงุฑ ุนุดูุงุฆูุฉ ุนูุฏ ุงูุชุดุบูู ุงููุฏูู ุงูุขู)
            ADKAR=("ุณูุจูุญูุงูู ุงูููููู ููุจูุญูููุฏููู" "ุฃูุณูุชูุบูููุฑู ุงูููููู ููุฃูุชููุจู ุฅููููููู" "ููุง ุญููููู ููููุง ูููููุฉู ุฅููููุง ุจูุงูููููู" "ุณูุจูุญูุงูู ุงูููููู ุงููุนูุธูููู" "ุงููููููููู ุตูููู ููุณูููููู ุนูููู ููุจููููููุง ููุญููููุฏู")
            for msg in "${ADKAR[@]}"; do
              curl -s -X POST "https://api.telegram.org/bot$TOKEN/sendMessage" \
              -d "chat_id=$CHANNEL" -d "parse_mode=HTML" \
              -d "text=$HEADER%0A%0A๐ <b>ูู ุฃุฐูุงุฑ ุงููุณุงุก</b>%0A%0A$msg"
              sleep 2
            done
          fi
